//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ModeloDeDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int idCarrinho { get; set; }
        public int qtdeItensVenda { get; set; }
        public decimal valorParcial { get; set; }
        public int idVenda { get; set; }
        public int idProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
