//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int idCarrinho { get; set; }
        public int qtdeProd { get; set; }
        public Nullable<int> FK_IdVendas { get; set; }
        public Nullable<int> FK_idProdutos { get; set; }
    
        public virtual Produtos Produtos { get; set; }
        public virtual Vendas Vendas { get; set; }
    }
}
